version: "{branch} #{build}"

shallow_clone: true

image:
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"

install:
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user

before_build:
  - if exist build RMDIR /S /Q build
  - if not exist build mkdir build
  - cd build

build_script:
  - cmake -G "%GENERATOR%" -A %PLATFORM% ..
  - cmake --build . --config %CONFIGURATION%

test_script:
  - ctest --output-on-failure -C %CONFIGURATION%
